// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: mcp.proto

package pdfprocessor

import (
	"context"

	"GoZero-AI/mcp/types/mcp"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Metadata = mcp.Metadata
	PdfReq   = mcp.PdfReq
	PdfRes   = mcp.PdfRes

	PdfProcessor interface {
		// ExtractTextFromPDF 流式PDF文本提取方法
		ExtractTextFromPDF(ctx context.Context, opts ...grpc.CallOption) (mcp.PdfProcessor_ExtractTextFromPDFClient, error)
	}

	defaultPdfProcessor struct {
		cli zrpc.Client
	}
)

func NewPdfProcessor(cli zrpc.Client) PdfProcessor {
	return &defaultPdfProcessor{
		cli: cli,
	}
}

// ExtractTextFromPDF 流式PDF文本提取方法
func (m *defaultPdfProcessor) ExtractTextFromPDF(ctx context.Context, opts ...grpc.CallOption) (mcp.PdfProcessor_ExtractTextFromPDFClient, error) {
	client := mcp.NewPdfProcessorClient(m.cli.Conn())
	return client.ExtractTextFromPDF(ctx, opts...)
}
