// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type InterviewAppChatReq struct {
	Message string `form:"message"`
	ChatId  string `form:"chatId"`
	Mode    string `form:"mode,optional"`
}

type KnowledgeTextUploadReq struct {
	Title   string `json:"title"`
	Content string `json:"content"`
	Source  string `json:"source,optional"`
}

type KnowledgeUploadReq struct {
	File string `form:"file"`
}

type KnowledgeUploadRes struct {
	Msg    string `json:"msg"`
	Chunks int    `json:"chunks"`
}
