// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type ChatRes struct {
	Content  string `json:"content"`
	IsLatest bool   `json:"isLatest"`
}

type InterviewAppChatReq struct {
	Message string `form:"message"`
	ChatId  string `form:"chatId"`
}
