// mcp.proto - MCP (Message Communication Protocol) gRPC 服务契约定义
// 这是GoZero-AI项目中的核心gRPC服务定义文件，负责PDF文档处理的微服务通信协议
//
// 主要功能:
//  1. PDF文档上传与解析 - 支持大文件流式传输，避免内存溢出
//  2. 文本内容提取 - 将PDF文档转换为纯文本，供RAG系统使用
//  3. 错误处理机制 - 提供完整的错误信息反馈
//  4. 元数据管理 - 支持文件名、MIME类型等文件属性传递
//
// 技术特性:
//   - 使用Protocol Buffers 3.0语法
//   - 支持双向流式RPC，适合大文件处理
//   - 采用分块传输机制，提高传输效率
//   - 兼容GoZero框架的gRPC生成工具
//
// 应用场景:
//   - 企业文档管理系统的文档解析
//   - RAG知识库构建中的PDF文档预处理
//   - 智能文档分析系统的文本提取
//   - 大规模文档批处理系统
//
// 架构设计:
//   - 客户端: GoZero-AI/api 服务 (HTTP -> gRPC转换)
//   - 服务端: GoZero-AI/mcp 服务 (gRPC PDF处理器)
//   - 协议层: 本文件定义的gRPC接口契约
//
// 生成代码命令:
//   在 /mcp 目录下执行:
//   goctl rpc protoc mcp.proto --go_out=./types --go-grpc_out=./types --zrpc_out=.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.19.4
// source: mcp.proto

// 包名定义 - 用于生成Go代码的包结构

package mcp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PdfReq PDF处理请求消息
// 使用oneof联合类型支持不同阶段的数据传输
//
// 设计模式: 状态机模式
//
//	状态1: 发送元数据 (metadata字段)
//	状态2: 发送文件数据块 (chunk字段)
//
// 数据流设计:
//
//	第一条消息: PdfReq{metadata: Metadata{filename: "doc.pdf", mime_type: "application/pdf"}}
//	后续消息:   PdfReq{chunk: []byte{PDF二进制数据}}
//
// 优势分析:
//   - 类型安全: oneof确保每条消息只包含一种类型的数据
//   - 内存效率: 避免同时传输元数据和大块数据
//   - 协议清晰: 明确区分控制信息和数据信息
type PdfReq struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*PdfReq_Metadata
	//	*PdfReq_Chunk
	Data          isPdfReq_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfReq) Reset() {
	*x = PdfReq{}
	mi := &file_mcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfReq) ProtoMessage() {}

func (x *PdfReq) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfReq.ProtoReflect.Descriptor instead.
func (*PdfReq) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{0}
}

func (x *PdfReq) GetData() isPdfReq_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *PdfReq) GetMetadata() *Metadata {
	if x != nil {
		if x, ok := x.Data.(*PdfReq_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *PdfReq) GetChunk() []byte {
	if x != nil {
		if x, ok := x.Data.(*PdfReq_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isPdfReq_Data interface {
	isPdfReq_Data()
}

type PdfReq_Metadata struct {
	Metadata *Metadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // 文件元数据信息 - 仅在首条消息中使用
}

type PdfReq_Chunk struct {
	Chunk []byte `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"` // 文件数据块 - 在后续消息中分块传输文件内容
}

func (*PdfReq_Metadata) isPdfReq_Data() {}

func (*PdfReq_Chunk) isPdfReq_Data() {}

// PdfRes PDF处理响应消息
// 服务端向客户端返回处理结果和状态信息
//
// 响应类型:
//  1. **进度响应**: content包含部分解析结果，error为空
//  2. **成功响应**: content包含完整文本内容，error为空
//  3. **错误响应**: content为空，error包含错误描述
//
// 使用场景:
//   - 实时反馈: 客户端可以实时显示解析进度
//   - 错误处理: 详细的错误信息帮助诊断问题
//   - 结果传递: 高效传输解析后的文本内容
//
// **后续**优化方向:
//   - 添加progress字段显示解析百分比
//   - 添加page_count字段显示总页数信息
//   - 支持结构化内容返回 (章节、表格等)
type PdfRes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Content       string                 `protobuf:"bytes,1,opt,name=content,proto3" json:"content,omitempty"` // 解析后的文本内容 - 可能是部分内容(流式)或完整内容(最终)
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`     // 错误信息 - 当处理失败时包含具体的错误描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PdfRes) Reset() {
	*x = PdfRes{}
	mi := &file_mcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PdfRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PdfRes) ProtoMessage() {}

func (x *PdfRes) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PdfRes.ProtoReflect.Descriptor instead.
func (*PdfRes) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{1}
}

func (x *PdfRes) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *PdfRes) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Metadata 文件元数据信息
// 包含PDF文件的基本属性信息，用于处理前的验证和配置
//
// 字段说明:
//
//	filename: 原始文件名，用于日志记录和结果追踪
//	mime_type: MIME类型，用于文件格式验证
//
// 验证规则:
//   - filename: 必须非空，建议包含文件扩展名
//   - mime_type: 必须为"application/pdf"或相关PDF MIME类型
//
// 扩展字段 (**后续**可能添加):
//   - file_size: 文件大小，用于进度计算
//   - checksum: 文件校验和，确保传输完整性
//   - encoding: 文件编码信息
//   - creation_time: 文件创建时间
type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`                 // 文件名 - 原始PDF文件的名称，用于标识和日志记录
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"` // MIME类型 - 文件的媒体类型，通常为"application/pdf"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_mcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_mcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_mcp_proto_rawDescGZIP(), []int{2}
}

func (x *Metadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Metadata) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

var File_mcp_proto protoreflect.FileDescriptor

const file_mcp_proto_rawDesc = "" +
	"\n" +
	"\tmcp.proto\x12\x03mcp\"U\n" +
	"\x06PdfReq\x12+\n" +
	"\bmetadata\x18\x01 \x01(\v2\r.mcp.MetadataH\x00R\bmetadata\x12\x16\n" +
	"\x05chunk\x18\x02 \x01(\fH\x00R\x05chunkB\x06\n" +
	"\x04data\"8\n" +
	"\x06PdfRes\x12\x18\n" +
	"\acontent\x18\x01 \x01(\tR\acontent\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"C\n" +
	"\bMetadata\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType2B\n" +
	"\fPdfProcessor\x122\n" +
	"\x12ExtractTextFromPDF\x12\v.mcp.PdfReq\x1a\v.mcp.PdfRes\"\x00(\x01B\aZ\x05./mcpb\x06proto3"

var (
	file_mcp_proto_rawDescOnce sync.Once
	file_mcp_proto_rawDescData []byte
)

func file_mcp_proto_rawDescGZIP() []byte {
	file_mcp_proto_rawDescOnce.Do(func() {
		file_mcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)))
	})
	return file_mcp_proto_rawDescData
}

var file_mcp_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_mcp_proto_goTypes = []any{
	(*PdfReq)(nil),   // 0: mcp.PdfReq
	(*PdfRes)(nil),   // 1: mcp.PdfRes
	(*Metadata)(nil), // 2: mcp.Metadata
}
var file_mcp_proto_depIdxs = []int32{
	2, // 0: mcp.PdfReq.metadata:type_name -> mcp.Metadata
	0, // 1: mcp.PdfProcessor.ExtractTextFromPDF:input_type -> mcp.PdfReq
	1, // 2: mcp.PdfProcessor.ExtractTextFromPDF:output_type -> mcp.PdfRes
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_mcp_proto_init() }
func file_mcp_proto_init() {
	if File_mcp_proto != nil {
		return
	}
	file_mcp_proto_msgTypes[0].OneofWrappers = []any{
		(*PdfReq_Metadata)(nil),
		(*PdfReq_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_mcp_proto_rawDesc), len(file_mcp_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_mcp_proto_goTypes,
		DependencyIndexes: file_mcp_proto_depIdxs,
		MessageInfos:      file_mcp_proto_msgTypes,
	}.Build()
	File_mcp_proto = out.File
	file_mcp_proto_goTypes = nil
	file_mcp_proto_depIdxs = nil
}
