// mcp.proto - MCP (Message Communication Protocol) gRPC 服务契约定义
// 这是GoZero-AI项目中的核心gRPC服务定义文件，负责PDF文档处理的微服务通信协议
//
// 主要功能:
//  1. PDF文档上传与解析 - 支持大文件流式传输，避免内存溢出
//  2. 文本内容提取 - 将PDF文档转换为纯文本，供RAG系统使用
//  3. 错误处理机制 - 提供完整的错误信息反馈
//  4. 元数据管理 - 支持文件名、MIME类型等文件属性传递
//
// 技术特性:
//   - 使用Protocol Buffers 3.0语法
//   - 支持双向流式RPC，适合大文件处理
//   - 采用分块传输机制，提高传输效率
//   - 兼容GoZero框架的gRPC生成工具
//
// 应用场景:
//   - 企业文档管理系统的文档解析
//   - RAG知识库构建中的PDF文档预处理
//   - 智能文档分析系统的文本提取
//   - 大规模文档批处理系统
//
// 架构设计:
//   - 客户端: GoZero-AI/api 服务 (HTTP -> gRPC转换)
//   - 服务端: GoZero-AI/mcp 服务 (gRPC PDF处理器)
//   - 协议层: 本文件定义的gRPC接口契约
//
// 生成代码命令:
//   在 /mcp 目录下执行:
//   goctl rpc protoc mcp.proto --go_out=./types --go-grpc_out=./types --zrpc_out=.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.4
// source: mcp.proto

// 包名定义 - 用于生成Go代码的包结构

package mcp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PdfProcessor_ExtractTextFromPDF_FullMethodName = "/mcp.PdfProcessor/ExtractTextFromPDF"
)

// PdfProcessorClient is the client API for PdfProcessor service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PdfProcessor gRPC服务定义
// 专门处理PDF文档的解析和文本提取功能
//
// 设计理念:
//  1. **流式处理** - 支持大文件上传，避免内存限制
//  2. **实时响应** - 边上传边处理，提高用户体验
//  3. **错误隔离** - 独立的PDF处理服务，不影响主应用
//  4. **可扩展性** - 微服务架构，便于水平扩展
//
// 使用模式:
//
//	客户端发送: Metadata -> Chunk1 -> Chunk2 -> ... -> ChunkN
//	服务端返回: Progress -> Progress -> ... -> FinalContent
//
// 性能优势:
//   - 内存占用低: 分块处理，不需要将整个文件加载到内存
//   - 传输效率高: 流式传输，支持并发处理
//   - 故障恢复: 可以在传输中断后从断点继续
type PdfProcessorClient interface {
	// ExtractTextFromPDF 流式PDF文本提取方法
	// 接收PDF文件流，返回解析后的文本内容流
	//
	// 处理流程:
	//  1. 客户端首先发送包含文件元数据的PdfReq
	//  2. 然后分块发送PDF文件的二进制数据
	//  3. 服务端实时处理并返回解析进度和结果
	//  4. 最终返回完整的文本内容
	//
	// 错误处理:
	//   - 文件格式错误: 返回格式不支持的错误信息
	//   - 文件损坏: 返回解析失败的具体原因
	//   - 网络中断: 支持重新连接和断点续传
	//
	// **后续**扩展可能:
	//   - 支持多种文档格式 (Word, PowerPoint等)
	//   - 添加OCR文字识别功能
	//   - 支持文档结构化解析
	//   - 集成文档安全检查
	ExtractTextFromPDF(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PdfReq, PdfRes], error)
}

type pdfProcessorClient struct {
	cc grpc.ClientConnInterface
}

func NewPdfProcessorClient(cc grpc.ClientConnInterface) PdfProcessorClient {
	return &pdfProcessorClient{cc}
}

func (c *pdfProcessorClient) ExtractTextFromPDF(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PdfReq, PdfRes], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &PdfProcessor_ServiceDesc.Streams[0], PdfProcessor_ExtractTextFromPDF_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PdfReq, PdfRes]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PdfProcessor_ExtractTextFromPDFClient = grpc.ClientStreamingClient[PdfReq, PdfRes]

// PdfProcessorServer is the server API for PdfProcessor service.
// All implementations must embed UnimplementedPdfProcessorServer
// for forward compatibility.
//
// PdfProcessor gRPC服务定义
// 专门处理PDF文档的解析和文本提取功能
//
// 设计理念:
//  1. **流式处理** - 支持大文件上传，避免内存限制
//  2. **实时响应** - 边上传边处理，提高用户体验
//  3. **错误隔离** - 独立的PDF处理服务，不影响主应用
//  4. **可扩展性** - 微服务架构，便于水平扩展
//
// 使用模式:
//
//	客户端发送: Metadata -> Chunk1 -> Chunk2 -> ... -> ChunkN
//	服务端返回: Progress -> Progress -> ... -> FinalContent
//
// 性能优势:
//   - 内存占用低: 分块处理，不需要将整个文件加载到内存
//   - 传输效率高: 流式传输，支持并发处理
//   - 故障恢复: 可以在传输中断后从断点继续
type PdfProcessorServer interface {
	// ExtractTextFromPDF 流式PDF文本提取方法
	// 接收PDF文件流，返回解析后的文本内容流
	//
	// 处理流程:
	//  1. 客户端首先发送包含文件元数据的PdfReq
	//  2. 然后分块发送PDF文件的二进制数据
	//  3. 服务端实时处理并返回解析进度和结果
	//  4. 最终返回完整的文本内容
	//
	// 错误处理:
	//   - 文件格式错误: 返回格式不支持的错误信息
	//   - 文件损坏: 返回解析失败的具体原因
	//   - 网络中断: 支持重新连接和断点续传
	//
	// **后续**扩展可能:
	//   - 支持多种文档格式 (Word, PowerPoint等)
	//   - 添加OCR文字识别功能
	//   - 支持文档结构化解析
	//   - 集成文档安全检查
	ExtractTextFromPDF(grpc.ClientStreamingServer[PdfReq, PdfRes]) error
	mustEmbedUnimplementedPdfProcessorServer()
}

// UnimplementedPdfProcessorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPdfProcessorServer struct{}

func (UnimplementedPdfProcessorServer) ExtractTextFromPDF(grpc.ClientStreamingServer[PdfReq, PdfRes]) error {
	return status.Errorf(codes.Unimplemented, "method ExtractTextFromPDF not implemented")
}
func (UnimplementedPdfProcessorServer) mustEmbedUnimplementedPdfProcessorServer() {}
func (UnimplementedPdfProcessorServer) testEmbeddedByValue()                      {}

// UnsafePdfProcessorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PdfProcessorServer will
// result in compilation errors.
type UnsafePdfProcessorServer interface {
	mustEmbedUnimplementedPdfProcessorServer()
}

func RegisterPdfProcessorServer(s grpc.ServiceRegistrar, srv PdfProcessorServer) {
	// If the following call pancis, it indicates UnimplementedPdfProcessorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PdfProcessor_ServiceDesc, srv)
}

func _PdfProcessor_ExtractTextFromPDF_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(PdfProcessorServer).ExtractTextFromPDF(&grpc.GenericServerStream[PdfReq, PdfRes]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type PdfProcessor_ExtractTextFromPDFServer = grpc.ClientStreamingServer[PdfReq, PdfRes]

// PdfProcessor_ServiceDesc is the grpc.ServiceDesc for PdfProcessor service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PdfProcessor_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mcp.PdfProcessor",
	HandlerType: (*PdfProcessorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExtractTextFromPDF",
			Handler:       _PdfProcessor_ExtractTextFromPDF_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "mcp.proto",
}
