// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.5

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	knowledgeBaseFieldNames          = builder.RawFieldNames(&KnowledgeBase{}, true)
	knowledgeBaseRows                = strings.Join(knowledgeBaseFieldNames, ",")
	knowledgeBaseRowsExpectAutoSet   = strings.Join(stringx.Remove(knowledgeBaseFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	knowledgeBaseRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(knowledgeBaseFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	knowledgeBaseModel interface {
		Insert(ctx context.Context, data *KnowledgeBase) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*KnowledgeBase, error)
		Update(ctx context.Context, data *KnowledgeBase) error
		Delete(ctx context.Context, id int64) error
	}

	defaultKnowledgeBaseModel struct {
		conn  sqlx.SqlConn
		table string
	}

	KnowledgeBase struct {
		Id        int64     `db:"id"`         // 知识条目的唯一标识符 (主键)
		Title     string    `db:"title"`      // 知识条目的标题，便于管理和识别
		Content   string    `db:"content"`    // 知识条目的原始文本内容
		Embedding string    `db:"embedding"`  // 由文本内容生成的高维向量，用于相似度检索
		CreatedAt time.Time `db:"created_at"` // 知识条目的创建时间戳
		UserId    int64     `db:"user_id"`    // 知识的所有者ID。业务约定 user_id = 1 为管理员上传的公共知识。
	}
)

func newKnowledgeBaseModel(conn sqlx.SqlConn) *defaultKnowledgeBaseModel {
	return &defaultKnowledgeBaseModel{
		conn:  conn,
		table: `"public"."knowledge_base"`,
	}
}

func (m *defaultKnowledgeBaseModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultKnowledgeBaseModel) FindOne(ctx context.Context, id int64) (*KnowledgeBase, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", knowledgeBaseRows, m.table)
	var resp KnowledgeBase
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultKnowledgeBaseModel) Insert(ctx context.Context, data *KnowledgeBase) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4)", m.table, knowledgeBaseRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Title, data.Content, data.Embedding, data.UserId)
	return ret, err
}

func (m *defaultKnowledgeBaseModel) Update(ctx context.Context, data *KnowledgeBase) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, knowledgeBaseRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.Title, data.Content, data.Embedding, data.UserId)
	return err
}

func (m *defaultKnowledgeBaseModel) tableName() string {
	return m.table
}
