// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5

package types

type LoginReq struct {
	Username string `json:"username" validate:"required"`
	Password string `json:"password" validate:"required"`
}

type LoginResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpireIn     int64  `json:"expireIn"`
}

type LogoutReq struct {
}

type LogoutResp struct {
}

type RefreshTokenReq struct {
	RefreshToken string `json:"refreshToken" validate:"required"`
}

type RefreshTokenResp struct {
	AccessToken  string `json:"accessToken"`
	RefreshToken string `json:"refreshToken"`
	ExpireIn     int64  `json:"expireIn"`
}

type RegisterReq struct {
	Username        string `json:"username" validate:"required,min=6,max=50"`
	Password        string `json:"password" validate:"required,min=6,max=50"`
	ConfirmPassword string `json:"confirmPassword" validate:"required,eqfield=Password"`
}

type RegisterResp struct {
}
