// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.5
// Source: mcp.proto

package server

import (
	"GoZero-AI/mcp/internal/logic"
	"GoZero-AI/mcp/internal/svc"
	"GoZero-AI/mcp/types/mcp"
)

type PdfProcessorServer struct {
	svcCtx *svc.ServiceContext
	mcp.UnimplementedPdfProcessorServer
}

func NewPdfProcessorServer(svcCtx *svc.ServiceContext) *PdfProcessorServer {
	return &PdfProcessorServer{
		svcCtx: svcCtx,
	}
}

// ExtractTextFromPDF 流式PDF文本提取方法
func (s *PdfProcessorServer) ExtractTextFromPDF(stream mcp.PdfProcessor_ExtractTextFromPDFServer) error {
	l := logic.NewExtractTextFromPDFLogic(stream.Context(), s.svcCtx)
	return l.ExtractTextFromPDF(stream)
}
